###
POST http://localhost:8080/api/image/plus
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="img1"; filename="image.png"

< ./image.png

--WebAppBoundary
Content-Disposition: form-data; name="img2"; filename="image_mask.png"

< ./image_mask.png

--WebAppBoundary--

###
